; PlatformIO Project Configuration File
; Smart Waste Management - ESP32 Edge Node
;
; Hardware:
;   Board: ESP32 DOIT DevKit V1
;   Sensors: AJ-SR04 Ultrasonic, NEO-6M GPS
;   Communication: REYAX RYLR998 LoRa Module

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
    mikalhart/TinyGPSPlus@^1.1.0
